Implementation of InvokeWMLMethod
ibm-watson-iot/functions pull request #408
Opened 2021-06-04 14:41 UTC by sedgewickmm18

added a function to bif.py

2021-06-07 13:57 UTC, pkohlmann requested changes

2021-06-07 13:57 UTC, pkohlmann commented on iotfunctions/bif.py
> +            logger.error('WML API Key invalid')
logger.error() in conjunction with 'raise Exception' leaves the stacktrace twice in logfile what is umfavourable. I would omit the logger.error() statement.

2021-06-07 13:57 UTC, pkohlmann commented on iotfunctions/bif.py
> +                print('WML Credentials ' , str(wml_credentials))
Remove print statement or replace it by logger.info/debug(). In this case, the log message contains credentials which are not supposed to show up in logfiles. Therefore remove line completely or obfuscate the credentials

2021-06-07 13:57 UTC, pkohlmann commented on iotfunctions/bif.py
> +                pass
You dump an error with stacktrace into logfile by logger.error() but you continue execution. I guess this should be a warning that there is an attempt to circumvent the missing constant. By the way, the 'pass' is not necessary.

2021-06-07 13:57 UTC, pkohlmann commented on iotfunctions/bif.py
> +                out = out + 'APIKey: ' + str(self.apikey) + '\n'
Do you really want to make the APIKey visible?

2021-06-07 15:28 UTC, sedgewickmm18 commented on iotfunctions/bif.py
> +            rows = [list(r) for i,r in s_df.iterrows()]
Using tolist() now

2021-06-08 07:36 UTC, pkohlmann approved these changes
All good now!

2021-06-08 09:51 UTC, merged